template = ""
rev_id = 4
template_sha = "156a8b834dacf74fc905a1ee460fe5eabb9556c6"

[replacements]
__LICENSE__ = "CC-BY-4.0"
__UND2C_SRC__ = "smj"
__UND2C_TRG__ = "se"
__UNDEFINED_SOURCE__ = "Lule Sámi"
__UNDEFINED_TARGET__ = "North Sámi"
__UND_SRC__ = "smj"
__UND_TRG__ = "sme"
